version: "3.8"

services:
  db:
    container_name: discounts-db
    image: postgres:13-alpine
    volumes:
      - discoutnsdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - 5432:5432

  redis:
    container_name: discounts-redis
    image: redis:6.0
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - discountredis:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

volumes:
  discoutnsdata: null
  discountredis: null