version: "3.8"

services:
  db:
    container_name: discounts-db
    image: postgres:13-alpine
    volumes:
      - discoutnsdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - 5432:5432

volumes:
  discoutnsdata: null